### PR TITLE
Fix validation and rendering bugs

### LINKED ISSUE #177: Titles are repeated after reaching 3 levels of nesting.
I noticed bunsen repeating the 2nd layer of titles once I had hit three levels of nesting.

Int he following example, only one "Foo" is expected:
screen shot 2016-09-02 at 7 11 50 pm

The example's model and view:
Bunsen Model:
```javascript
{
    "type": "object",
    "properties": {
      "nested": {
       "type": "object",
        "properties": {
          "foo": {
            "type": "object",
            "properties": {
              "foosValue": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
```

Bunsen View:
Note: _cellDefinitions was needed, otherwise the view failed to work._
```javascript
{
    "type": "form",
    "version": "2.0",
    "cellDefinitions": {
    },
    "cells": [
      {
        "children": [
          {
            "label": "Main",
            "model": "nested",
            "children": [
              {
                "label": "Foo",
                "model": "foo",
                "children": [
                  {
                    "label": "value",
                    "model": "foosValue"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
```

Workaround is to attempt to skip a layer of nesting by directly referencing the parent in the child:
```javascript
{
    "type": "form",
    "version": "2.0",
    "cellDefinitions": {
    },
    "cells": [
      {
        "children": [
          {
            "label": "Main",
           // skip setting "model": "nested" here.
            "children": [
              {
                "label": "Foo",
                // the child can directly references the 
                // "nested.foo" instead of relying on the
                // "parent" to set the context.  Limits the 
                // nesting to two levels.
                "model": "nested.foo",
                "children": [
                  {
                    "label": "value",
                    "model": "foosValue"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
```

### LINKED ISSUE #240: Cell model not applied properly to children?
*Model*

```json
{
  "properties": {
    "foo": {
      "properties": {
        "bar": {
          "properties": {
            "baz": {
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}
```

*View*

```json
{
  "cells": [
    {
      "children": [
        {
          "model": "baz"
        }
      ],
      "model": "foo.bar"
    }
  ],
  "type": "form",
  "version": "2.0"
}
```

### PR DESCRIPTION
**Pull request by sandersky**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

Resolves #177 
Resolves #240 

# CHANGELOG

* **Fixed** issue with duplicate section headings rendering under certain scenarios.
* **Fixed** validation bug where cell's `model` wasn't being applied to it's `children`.
* **Fixed** small visual regression with positioning of collapsible toggle handle.

### CODE REVIEW

**Comment by sandersky** [comment]
:+1:

File: addon/components/cell.js [hunk 1]
```diff
@@ -291,20 +299,23 @@ export default Component.extend(PropTypeMixin, {
...
       (mergedConfig.label && mergedConfig.children)
     )
   },
 
+  @readOnly
+  @computed('cellConfig')
+  isLeafNode (cellConfig) {
+    return (
+      cellConfig.model &&
+      (!cellConfig.children || cellConfig.children.length === 0)
```
Comment (sophypal) [inline addon/components/cell.js]: Does this work for the array form as well?

Comment (sandersky) [inline addon/components/cell.js]: Yes.
