### PR TITLE
Fix issue with defaults in object array item

### LINKED ISSUE #174: When an array has defaults, the first item added doesn't get the joke
As pointed out by `mstaffor` in Slack:

> quick question. for the example of the Model `Array with Defaults`, is there a reason that the first superhero added does not get supplied with the defaults, but the additional ones do ?

pasted_image_at_2016_08_31_09_22

That is certainly a bug.

### PR DESCRIPTION
**Pull request by sandersky**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

Resolves #174 

# CHANGELOG

* **Fixed** issue where first item added to an object array wasn't getting defaults applied.

### CODE REVIEW

File: addon/components/array-container.js [hunk 1]
```diff
@@ -310,11 +294,12 @@ export default Component.extend(PropTypeMixin, {
     onAddItem () {
       const bunsenId = this.get('bunsenId')
       const newItem = this._getEmptyItem()
+      const onChange = this.get('onChange')
       const value = this.get('value')
       const items = _.get(value, bunsenId) || []
       const index = items.length
 
-      this.notifyParentOfNewItem(newItem, index)
+      onChange(`${bunsenId}.${index}`, newItem)
```
Comment (cbeekciena) [inline addon/components/array-container.js]: So by calling onChange() you force a re-rendering, correct?

**Comment by agonza40** [comment]
👍

File: addon/components/array-container.js (hunk 1 above)
Comment (cbeekciena) [inline addon/components/array-container.js]: Matt's response, as discussed offline:

Yes b/c onChange propagates back up to the detail component, which in turn hands the change event off to the redux store (in bunsen-core), which ultimately updates the form value in the detail component
